INSERT INTO personne (Nom, Prenom, Civilite) VALUES
('Doe', 'John', 'M'),
('Smith', 'Jane', 'F'),
('Johnson', 'Michael', 'M'),
('Williams', 'Emily', 'F'),
('Brown', 'David', 'M'),
('Jones', 'Sarah', 'F'),
('Miller', 'Robert', 'M'),
('Davis', 'Jennifer', 'F'),
('Wilson', 'Daniel', 'M'),
('Taylor', 'Jessica', 'F'),
('Anderson', 'Christopher', 'M');

INSERT INTO Medecin (Id_Personne) VALUES
(4),
(5),
(6),
(7),
(8),
(9),
(10);

INSERT INTO personne (Nom, Prenom, Civilite)
VALUES
('Lee', 'Michelle', 'F'),
('Garcia', 'Carlos', 'M'),
('Lopez', 'Maria', 'F'),
('Martinez', 'Juan', 'M'),
('Hernandez', 'Ana', 'F'),
('Gonzalez', 'Pedro', 'M'),
('Rodriguez', 'Laura', 'F'),
('Perez', 'Luis', 'M'),
('Sanchez', 'Sofia', 'F'),
('Ramirez', 'Diego', 'M'),
('Torres', 'Isabella', 'F'),
('Flores', 'Miguel', 'M'),
('Rivera', 'Valentina', 'F'),
('Gomez', 'Alejandro', 'M'),
('Reyes', 'Camila', 'F'),
('Morales', 'Gabriel', 'M'),
('Ortiz', 'Lucia', 'F'),
('Vargas', 'Daniel', 'M'),
('Castillo', 'Emma', 'F'),
('Jimenez', 'Adrian', 'M'),
('Moreno', 'Julia', 'F'),
('Romero', 'David', 'M'),
('Alvarez', 'Sara', 'F'),
('Ramos', 'Samuel', 'M'),
('Gutierrez', 'Victoria', 'F'),
('Chavez', 'Alex', 'M'),
('Mendoza', 'Elena', 'F'),
('Ruiz', 'Max', 'M'),
('Santos', 'Sophia', 'F'),
('Valdez', 'Leo', 'M');


INSERT INTO medecin (Id_Personne)
VALUES
(11),
(12),
(13),
(14),
(15),
(16),
(17),
(18),
(19),
(20),
(21),
(22),
(23),
(24),
(25),
(26),
(27),
(28),
(29),
(30),
(31),
(32),
(33),
(34),
(35),
(36),
(37),
(38),
(39),
(40);

